title: Smarsh Financial Inc.
baseurl: /
permalink: '/:title/'
palette: blue
header:
  has_nav: true
  logo_img: ''
  menu:
    actions:
      - label: Learn More
        url: /signup
  title: Smarsh Financial Inc.
footer:
  content: '&copy; Smarsh Financial Inc. All rights reserved.'
  has_nav: true
  has_social: true
  has_subscribe: true
  links: []
  logo_img: /images/smarsh-logo-tm-white-large.png
  nav_title: Company
  social_title: Community
  subscribe_content: Stay up to date with our latest updates.
  subscribe_title: Subscribe
  tagline: Securing your financial future.
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
